name: Build

permissions:
  contents: write

on:
  push:
    branches:
      - next
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - runner: ubuntu-latest
            platform: linux
            arch: gcc_64
            exeSuffix: ''
          - runner: windows-latest
            platform: windows
            arch: win64_msvc2019_64
            exeSuffix: '.exe'
          - runner: macos-latest
            platform: mac
            arch: clang_64
            exeSuffix: ''

    runs-on: ${{ matrix.os.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup GCC
        run: |
          sudo apt install build-essential ninja-build
        if: ${{ matrix.os.platform == 'linux' }}

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
        if: ${{ matrix.os.platform == 'windows' }}

      - name: Setup Clang
        uses: ConorMacBride/install-package@v1.1.0
        with:
          brew: llvm ninja
        if: ${{ matrix.os.platform == 'mac' }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.3
          host: ${{ matrix.os.platform }}
          target: desktop
          arch: ${{ matrix.os.arch }}
          cache: true
          setup-python: false
          tools: 'tools_cmake tools_ninja'

      - name: Setup env for windows
        run: |
          echo "Qt6_DIR=$env:Qt6_DIR" >> $GITHUB_ENV
        if: ${{ matrix.os.platform == 'windows' }}

      - name: Cmake
        run: |
          mkdir build
          cmake -DCMAKE_PREFIX_PATH="${Qt6_DIR}/lib/cmake" -DCMAKE_BUILD_TYPE=Release -G Ninja -B build

      - name: Ninja
        run: |
          cd build
          ninja

      - name: Upload Artifacts
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: build/dynafx${{ matrix.os.exeSuffix }}
          asset_name: dynafx-${{ matrix.os.platform }}${{ matrix.os.exeSuffix }}

        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
